Create 2018-08-07.md
tc39/proposal-decorators pull request #138
Opened 2018-08-07 18:12 UTC by jridgewell

2018-08-07 18:18 UTC, rbuckton requested changes

2018-08-07 18:18 UTC, rbuckton commented on meetings/2018-08-07.md
> +        * RB: I hate having decorators before and after the export (one decorating the export and one decorating the class). I don’t think this is viable. 
I don't think I used the word "hate". I am opposed to having both.

2018-08-07 18:30 UTC, rbuckton approved these changes
Not sure if anyone else has other comments.

2018-08-08 00:29 UTC, ljharb commented on meetings/2018-08-07.md
> +    * Decorators aren't included in methods' toString (and neither is static) 
This isn't something I think we have consensus on.

2018-08-08 00:29 UTC, ljharb commented on meetings/2018-08-07.md
> +    * Dan's take: include static and decorators in method toString 
^ this is what i'd like to happen.

2018-08-08 12:14 UTC, merged